### ISSUE TITLE
Generating undo records by using pgreplay

### ISSUE THREAD

**Issue by gogo9th** [laurenz/pgreplay#16]
Hi,

Thanks a lot for making this amazing program. This will be super-useful for my future projects. 

I just have one question. I need to manually craft an anti-WAL file that will undo certain SQL operations done from within a regular WAL file. Suppose the SQL server has run query 1~100. At this point, I want the SQL server to undo query 10, 20, and 30 (suppose these 3 queries are INSERT to the same table). One way to do this is to create 3 SQL queries that DELETE the records inserted by query 10, 20, and 30. However, I want the SQL server to do this deletion operation not via SQL queries, but via low-level read/write operations as the ones specified in the WAL file. The reason is that SQL queries could contain complex conditions by using multiple JOINs, which will be slow. So I instead try to  create a special WAL file which will make the SQL server undo query 10, 20 and 30 once it starts up. I wonder if I could make such a program which crafts the WAL file by slightly modifying or leveraging your pgreplay source code. If you think this is possible, could you please give me some hint on ho & where I could start it from your source files? I would really appreciate your help.

**Comment by laurenz** [comment]
pgreplay does not operate on the WAL level at all, it reads text from the log file (which is quite different from the WAL file!).

But I'll share my thoughts on your &ldquo;undo&rdquo; idea with you.

I don't think that this is possible in the way you envision, because the WAL does not contain information which query lead to which binary change. Moreover, an `INSERT` will cause several operations: typically a heap item is added (the row) and there are several index operations. There is no was to determine which index operation belongs to which heap operation. And this is just scratching the surface. How would you want to undo an `UPDATE` operation where the dead tuple has been vacuumed away?

The best I can imagine is for you to write a logical decoding plugin that creates something like the inverse of the operations, but that will only work for `INSERT`s, because there is no undo information in the WAL. There still won't be a correspondence between the generated statements and the original ones.

I think this idea is pretty much doomed.
