### ISSUE TITLE
Error: unknown type 115 encountered

### ISSUE THREAD

**Issue by mvives-broadsign** [laurenz/pgreplay#5]
Hello Guys, 
After ~22 hours of running, my pgreplay ends with ```Error: unknown type 115 encountered```. I'm checking the CSV and they do not seem to contain any error. As I did not keep the aggregated CSV I used to generate the pgreplay file, I'm currently parsing it to see if it ends on the last statement (I'll keep this question updated with this info). 
I' ve rerun the replay in debug, and I am noticing that all the last statements it did before seeing this error are disconnects but I can not see them in the CSV files. Is it possible that there is an issue if my csv does not end with a disconnect (or ends in a middle of a transaction )

**Comment by laurenz** [comment]
That error is thrown when pgreplay encounters a corrupted replay file.

The 17th byte of each line must be the type of the command that should be replayed and is between 0 and 6. Somehow, pgreplay reads 115 in your case.

I'd suspect that the replay file got mangled somehow, but since it ran for 22 hour without problem, that seems unlikely.

Since your replay ran that long, it's probably hard to pinpoint which record in the file causes the problem.

I don't know how to find the problematic record...
This is how you can get the 17th character of each line in `replayfile`:

    cut -b 17 replayfile

Unless your statements contain newlines, that should only output bytes 0x00 to 0x06.

Perhaps you can figure out which line has the problem.

**Comment by laurenz** [comment]
If you see a lot of disconnects right before the problematic place, those might be disconnects that pgreplay adds automatically at the end. Perhaps your replay went well until the very end. What are the last couple of lines in the replay file?

**Comment by mvives-broadsign** [comment]
I found the issue,  sorry for making you lose your time :S
Following a bash mistake, the replay file ended with 
```
Parse statistics
================

Log lines read: 58938849
Total SQL statements processed: 24579666
Simple SQL statements processed: 24579666
(includes 87 ignored copy statements)
Parametrized SQL statements processed: 0
Named prepared SQL statements executions processed: 0
Cancel requests processed: 0
Fast-path function calls ignored: 0

```

**Comment by laurenz** [comment]
I'm happy to lose some time if there is somebody interested on the other end who doesn't mind investigating the problem himself.

That's the only way to keep the software working and improve it.
